name: Build and Release

on:
  push:
    tags:
      - 'v*' # Триггер на теги версий, например v1.0.3
  workflow_dispatch: # Возможность запустить вручную

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          out/make/squirrel.windows/x64/*.exe
          out/make/squirrel.windows/x64/*.nupkg
          out/make/squirrel.windows/x64/RELEASES
        draft: true
        prerelease: ${{ contains(github.ref_name, 'beta') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          out/make/squirrel.windows/x64/
