name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Необходимо для компиляции нативных модулей на Ubuntu
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxtst-dev libpng++-dev
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    # Вместо build используем package для Electron-приложения
    - name: Package application
      run: npm run package
      
    # Сборка артефактов только для Windows без запуска make
    - name: Upload Windows artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-windows
        path: out/cider-code-wh-app-win32-x64/