name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: TypeScript Check
      run: npx tsc --noEmit
      
    - name: Check formatting
      run: npm run format:check
      continue-on-error: false
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true